# Generated by Django 5.0.3 on 2024-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
