# Generated by Django 5.0.3 on 2024-03-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_service", "0004_remove_airport_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airports",
                to="airport_service.city",
            ),
            preserve_default=False,
        ),
    ]
