# Generated by Django 5.0.3 on 2024-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_service", "0005_airport_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
