# Generated by Django 5.0.3 on 2024-04-07 14:44

import airport_service.used_functions.image_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_service", "0006_alter_airport_city_delete_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplane",
            old_name="image",
            new_name="outside_image",
        ),
        migrations.AddField(
            model_name="airplane",
            name="inside_image",
            field=models.ImageField(
                null=True,
                upload_to=airport_service.used_functions.image_file_path.airplane_image_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrivals",
                to="airport_service.airport",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departures",
                to="airport_service.airport",
            ),
        ),
    ]
