# Generated by Django 5.0.3 on 2024-04-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_service", "0009_alter_ticket_options_alter_ticket_flight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport_service.flight",
            ),
        ),
    ]
